### ISSUE TITLE
Undefined offset: 2 Line 689

### ISSUE THREAD

**Issue by nicklee1990** [fennb/phirehose#93] opened 2015-10-16 20:27 UTC
Is anyone else seeing an issue with line 689?

     list($httpVer, $httpCode, $httpMessage) = preg_split('/\s+/', trim(fgets($this->conn, 1024)), 3);

It's producing the following error: Undefined offset: 2 but I haven't been able to work out what is going wrong

**Comment by DarrenCook** [comment] 2015-10-16 20:41
Duplicate of #81

**Closed** 2015-10-16 20:41 UTC
